theme: jekyll-theme-minimal
title: smiley
description: ผมชื่อนายศศิพงษ์ ชัยมัง(Sasipong Chaimung) อายุ 20 ปี เบอร์โทรศัพท์:0926890965 e-mail:pooh.18.11.48@gmail.com 
description: เข้าศึกษามหาวิทยาลัยในปี 67 กำลังศึกษาอยู่มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตกำแพงแสน คณะศิลปะศาสตร์และวิทยาศาสตร์ สาขาวิชาวิทยาการคอมพิวเตอร์ปีที่ 3 
description: ทักษะที่มี-เขียนโปรแกรมคอมพิวเตอร์ได้เบื้องต้น, รู้เกี่ยวกับdata base และระบบปฏิบัติการต่าง ๆเบื้องต้น การทำงานเป็นทีม 
description: ตอนนี้กำลังศึกษาเรื่องที่กำลังจะเป็นคอมพิวเตอร์กราฟิกเป็นอาชีพ จึงสร้าง Github นี้ขึ้นมานำเสนอผลงานที่เคยมีประสบการณ์ หรือได้ทำออกมาไว้ใน GitHub ของตนเอง 
description: มีทั้งเรื่องการสร้างรูปจากเส้น สร้างวงกลม ขยับขยาย, หมุนรูปภาพ สร้างภาพจาก Matrix การลงสีตั้งค่าสี และสร้างภาพเสมือนในเว็ป Desmos เป็นต้น